name: SimpleSpigot
main: org.xjcraft.SimpleSpigot
version: ${project.version}
author: reezhu
load: STARTUP
softdepend: [PlaceholderAPI,TitleAPI]


commands:
  config:
    description: 配置相关
    usage: use /config <save|dump|load|grep> <PluginName> 保存/导出/读取/查询插件
    permission: config.command
    permission-message: You don't have <permission>
    aliases: [ "cfg" ]

permissions:
  config.command:
    description: Allow user to use config command
    default: op